name: Dev Docker Image CI & CD

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    name: Running Compile Next Multi-arch Docker Main Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PicImpact
        uses: actions/checkout@v4
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: set_up_buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push main
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKER_REPO }}/${{ vars.DOCKER_GROUP }}/picimpact:dev
